from __future__ import annotations

import json
from pathlib import Path

WT = Path(__file__).resolve().parents[3]
PROGRAMME = WT / "research" / "programmes" / "002-henry-hub-fresh"
SCAN = json.loads((WT / ".work" / "changes" / "289-l0-l3-henry-hub-research" / "feasibility-scan.json").read_text())
OUT = PROGRAMME / "feasibility-ledger.json"


def entry(
    design_id: str,
    decision: str,
    sources: list[str],
    fidelity: str,
    raw_n: str,
    dependence: str,
    effective_info: str,
    mepi: str,
    detectable: str,
    sensitivity: str,
    blockers: list[str],
) -> dict[str, object]:
    return {
        "design_id": design_id,
        "decision": decision,
        "freeze_ready": False,
        "empirical_execution_authority": False,
        "source_identities": sources,
        "semantic_fidelity_class": fidelity,
        "eligible_raw_n": raw_n,
        "dependence_structure": dependence,
        "effective_information": effective_info,
        "mepi_derivation": mepi,
        "detectable_effect_screen": detectable,
        "power_sensitivity": sensitivity,
        "remaining_blockers": blockers,
    }


rows: list[dict[str, object]] = []
rows += [
entry("rep-001-samuelson-maturity-volatility", "GO", ["databento_henry_hub"], "near_replication_source_ready", "5,025 trade dates; 209 raw contract symbols; 135,384 mapped outright contract-days", "Repeated daily observations within contracts and common market shocks; contract and calendar dependence require clustered/block inference.", "209 contract identities is an optimistic cluster-count screen, not independent daily N.", "Literature requires a monotone maturity-volatility pattern; no defensible paper-magnitude MEPI was recovered, so numeric MEPI remains a freeze blocker.", "Standardized cluster-count screen: 2.802/sqrt(209) = 0.194 SD; actual detectable effect must be recomputed with contract/calendar dependence.", "Source/sample capacity is strong. Final power must use the implemented ordered-contrast covariance, not raw rows.", ["derive numeric scientific MEPI before freeze", "implementation-specific clustered power simulation"]),
entry("rep-002-seasonal-forward-curve", "GO", ["databento_henry_hub"], "mechanism_replication_source_ready", "4,987 dates with >=6 maturities; 4,575 with >=12; 4,487 with >=13; all 195 overlapping months have a >=13-maturity date", "Curve snapshots are serially dependent and seasonal comparisons repeat within calendar years.", "17 calendar years is the conservative year-block information count; 195 months is the unadjusted upper-bound row count.", "MEPI should be a literature/decision-relevant standardized seasonal slope shift; numeric value not yet justified from the source literature.", "Screen spans about 0.201 SD at raw monthly N=195 to 0.680 SD at 17 independent year blocks.", "Can implement now; small seasonal effects may remain unresolved after block dependence.", ["derive numeric MEPI", "year-block/bootstrap power simulation"]),
entry("rep-003-storage-surprise-response", "HOLD", ["eia_storage", "databento_henry_hub", "Bloomberg weekly natural-gas storage consensus"], "source_faithful_consensus_not_proven_accessible", "106 PIT EIA releases join market dates; consensus-qualified N unknown until Bloomberg history is audited", "Release-event dependence is modest, but surprise construction is impossible without a fixed pre-release expectation series.", "No valid effective N can be assigned before consensus-qualified events are counted.", "Literature sign is anchored, but magnitude MEPI must be recovered or decision-anchored before freeze.", "Not computable until consensus-qualified event N is known.", "Market/release layer is ready; expectation layer is the binding blocker.", ["prove Bloomberg historical entitlement/extractability", "prove consensus timestamp fixity before each release", "count consensus-qualified events"]),
]
rows += [
entry("rep-004-storage-state-nonlinearity", "GO", ["eia_storage revised historical truth", "databento_henry_hub"], "mechanism_replication_historical_truth_only", "844 weekly storage observations across 195 months / 17 years from 2010-06-11 through 2026-08-07", "Storage state is extremely persistent; simple week-of-year storage-anomaly AR(1) rho is about 0.991.", "A deliberately severe scalar AR(1) screen gives N_eff about 4; year-block information is 17. Threshold/SVAR implementation may contain more information and needs model-specific simulation.", "Source literature establishes regime differences qualitatively; a numeric MEPI has not yet been recovered.", "Standardized screening bound is about 0.680 SD using 17 year blocks and 1.401 SD using the severe AR(1) N_eff=4 screen.", "Implementation may proceed, but small regime effects cannot be assumed resolvable. Power is a mandatory pre-freeze gate.", ["fix threshold/state rule before market-outcome analysis", "model-specific threshold/SVAR power simulation", "derive numeric MEPI"]),
entry("rep-005-scarcity-volatility", "GO", ["eia_storage revised historical truth", "databento_henry_hub"], "near_replication_historical_truth_only", "844 weekly storage rows; 206 winter rows; 95 winter rows below full-sample mean and 96 winter rows below week-of-year seasonal norm", "Storage state is highly persistent and winter/scarcity cells repeat within years.", "17 year blocks are the conservative seasonal-cycle count; scalar storage-anomaly AR(1) N_eff about 4 is a pessimistic lower screen.", "Literature requires stronger negative inventory-volatility relation in scarcity/winter; numeric magnitude MEPI is unresolved.", "Dependence-sensitive screen is roughly 0.680 to 1.401 SD; cell-specific implemented contrast may differ.", "Source and cell counts support implementation, not a claim of high power. Final interaction power must be simulated.", ["derive numeric MEPI", "predeclare scarcity definition", "interaction/block-bootstrap power simulation"]),
entry("rep-006-inventory-forward-curve-scarcity", "GO", ["databento_henry_hub", "eia_storage revised historical truth", "public one-year U.S. Treasury/FRED candidate"], "near_replication_measurement_route_ready", "195 monthly storage months; every month has at least one date with >=13 simultaneously listed NG maturities", "Monthly storage and curve state are serially dependent; annual seasonality creates clustered information.", "195 months is raw upper bound; 17 year blocks is conservative lower information count.", "Literature anchors direction/seasonality-filtered scarcity relation; numeric magnitude MEPI still needs source recovery or decision justification.", "Standardized screen ranges from 0.201 SD at raw N=195 to 0.680 SD at 17 year blocks.", "Exact front/13th curve construction is feasible throughout the overlap.", ["acquire and pin one-year rate source", "recover/fix exact monthly sampling and deseasonalization formula", "derive numeric MEPI and block power"]),
]
rows += [
entry("rep-007-weather-return-volatility-response", "REDESIGN", ["Mu 2007", "Chen-Hartley-Lan 2023", "repository open_meteo_v1 issued forecasts"], "current_repository_weather_source_not_source_faithful_for_reproduction", "Repository has 723 immutable issued-weather snapshots from 2024-08-13 through 2026-08-12 with 7 declared missing dates and 618 exact source-date/market-date intersections", "Only about two annual cycles are present and the stored information set is issued forecast data, not the long-run realized-weather/climatology shock construction used by the reproduction literature.", "Raw date count would materially overstate independent seasonal information; no valid reproduction N_eff is assigned until a source-faithful observed-weather/climatology series is constructed.", "Literature defines directional weather-shock effects, but a source-faithful variable and numeric MEPI must be fixed before power is meaningful.", "The apparent raw-date screen (0.113 SD at N=618) is invalid for reproduction power because source fidelity and seasonal dependence are unresolved.", "Do not execute this reproduction on the 2024+ issued archive. Build the literature-compatible observed-weather/climatology layer first.", ["select source-faithful NOAA/USCRN or paper-specific observed-weather source", "recover weighting/climatology/shock definition", "recount season cells and recompute power"]),
entry("rep-008-weather-season-sign-asymmetry", "REDESIGN", ["Ergen-Rizvanoghlu 2016", "repository open_meteo_v1 issued forecasts"], "current_repository_weather_source_not_source_faithful_for_reproduction", "723 issued-weather source dates only; source-faithful season x sign shock cells not constructible yet", "Strong season/sign stratification plus serial weather dependence; two-year issued archive cannot establish literature-equivalent cells.", "No valid N_eff until the observed-weather departure series and fixed asymmetry cells are constructed.", "Literature anchors asymmetry by season/sign, but numeric cell-level MEPI is unresolved.", "Not computable for the reproduction design from the current issued-weather archive.", "Requires source redesign before implementation; otherwise it would answer a different question.", ["construct source-faithful weather departures", "predeclare season/sign cells", "count cells and run multiplicity-aware power screen"]),
entry("rep-009-announcement-volatility", "GO", ["eia_storage PIT release calendar", "databento_henry_hub"], "near_replication_event_calendar_ready", "106 verified storage releases from 2024-08-01 through 2026-08-06; all 106 join a canonical market date; 97 Thu, 5 Wed, 3 Fri, 1 Mon", "Event days are sparse relative to controls; volatility observations remain serially dependent.", "106 release events is the event-count screen; implemented HAC/year-block inference must account for market dependence.", "Literature requires elevated announcement-day volatility; numeric magnitude MEPI is unresolved.", "Approximate standardized event-versus-large-control screen is about 0.272-0.276 SD before serial-dependence inflation.", "The release-calendar/sample gate passes. Holiday-shifted releases are explicitly represented.", ["derive numeric MEPI", "fix matched-control/calendar rule", "HAC/year-block power simulation"]),
]
rows += [
entry("rep-010-volatility-state-dependence", "REDESIGN", ["databento_henry_hub", "eia_storage revised historical truth", "eia_storage PIT release calendar", "source-faithful observed weather pending"], "joint_primary_state_set_not_semantically_uniform", "Market: 5,025 trade dates; storage history: 844 weeks / 17 years; announcements: 106 releases; current issued weather: 723 snapshots / 618 exact market-date intersections", "The state families have different grains and dependence. Storage is extremely persistent, event days are sparse, and the current weather source is not faithful to the observed-weather reproduction literature.", "No defensible single N_eff exists for the current joint test. Each state family needs its own effective-information calculation before a joint synthesis is defined.", "A joint MEPI is not scientifically interpretable until the primary state families are source-faithful and their estimands are normalized.", "Not computable for the current joint primary because component information scales are heterogeneous and one required family has a fidelity failure.", "Split the current joint primary into source-faithful family-specific reproductions; synthesize state dependence only after those component designs are valid.", ["redesign primary around separately valid state-family estimands", "replace issued-weather reproduction input with source-faithful observed weather", "derive component MEPIs and family-specific power before synthesis"]),
entry("rep-011-weather-enhanced-volatility-oos", "HOLD", ["Liang et al. 2022", "source-study EIA Henry Hub 1-month futures", "historical New York/Louisiana weather source pending verification"], "source_study_route_identified_weather_provider_and_formula_unverified", "Source study states 1995-01 through 2021-07 with in-sample through 2017-08; exact usable daily N cannot be assigned until the weather source/model construction is recovered", "Daily volatility and low-frequency weather components are serially dependent; OOS loss differences are also dependent over forecast origins.", "Unknown until the source-study dataset/model is reconstructed. Raw calendar length must not be treated as independent forecast-comparison N.", "Recover the paper's reported forecast-loss magnitude or define a programme-decision MEPI only after the exact primary loss metric is verified.", "Not computable until source weather, model formulas, target and OOS loss metric are recovered.", "The exact market-period route is known, but the current 2024+ issued-weather archive is not a valid substitute.", ["verify exact weather provider/series/frequency", "recover exact GARCH-MIDAS formulas and primary OOS loss metric", "reconstruct source-study sample and dependence-aware power"]),
entry("rep-012-physical-balance-drivers", "REDESIGN", ["eia_fundamentals current revised history", "eia_storage revised historical truth", "databento_henry_hub", "source-faithful observed weather pending"], "broad_mechanism_sources_exist_but_joint_primary_mixes_semantics_and_frequencies", "EIA bulk contains 16,058 series with deep production, consumption, trade/LNG, power and Henry Hub histories; comparable joint N is undefined until exact series/frequency are fixed", "Monthly/weekly physical series are persistent and publication/revision semantics differ by family; forcing one complete-case block would discard information and blur the literature mechanisms.", "No valid joint N_eff before the physical families, grain, transformations and observed-weather route are fixed.", "A single block-level MEPI is not justified across heterogeneous balance mechanisms; family-specific scientific MEPIs are required.", "Not computable for the current omnibus design.", "Redesign into literature/source-specific balance sub-designs at the slowest defensible frequency, then synthesize only after each mechanism is source-faithful.", ["split physical-balance families into explicit source-study mechanisms", "fix observed-weather source where weather enters", "fix frequency/publication/revision semantics per family", "derive family MEPIs and dependence-aware power"]),
]
rows += [
entry("rep-013-lng-export-demand-channel", "HOLD", ["eia_fundamentals current revised history", "US-LNG-EBB public pipeline informational-posting route"], "public_candidate_route_found_source_contract_incomplete", "EIA bulk has deep LNG/export metadata, but national terminal-linked capacity/feedgas observations with verified posting-time history have not been counted", "Terminal/pipeline series will be persistent and cross-correlated; national aggregation cannot be assigned until terminal-to-pipeline coverage is established.", "Unknown until terminal mapping, historical depth, posting-time semantics and fleet coverage produce an eligible panel.", "Literature supplies the demand-channel direction, but a numeric capacity/feedgas MEPI still needs literature recovery or programme justification.", "Not computable before the source contract and eligible N are established.", "A public route exists in principle, but source fidelity is not ready for implementation.", ["prove terminal-pipeline mapping and national coverage", "audit historical depth and posting-time semantics", "separate capacity availability from scheduled/feedgas utilization", "count eligible observations and derive power"]),
entry("rep-014-monthly-real-time-forecastability", "GO", ["LIT-BHLR-RTDB author JAE real-time database and replication code"], "exact_replication_route_identified", "Authors' frozen real-time database spans vintages from 1991 with source-study monthly forecast origins and 1-24 month horizons; exact origin-by-horizon counts await package import", "Forecast errors and overlapping 1-24 month horizons are serially/cross-horizon dependent; horizon-family multiplicity must be retained.", "Exact effective information must be computed from the imported source-study origin/horizon panel; calendar months are only an upper bound.", "Use source-study reported MSPE improvements where recoverable as literature anchors, with a programme-decision floor fixed before execution where the paper does not supply a sufficient magnitude threshold.", "Deferred until exact package import establishes origin counts, overlapping-horizon structure and benchmark loss scale.", "The exact public replication route removes the data-vintage feasibility blocker. GO authorizes implementation/reconstruction only, not outcome execution or freeze.", ["import and hash exact JAE archive/code", "verify source-study target/benchmark/formulas and origin-by-horizon counts", "derive horizon-family MEPI and dependence-aware detectable effects"]),
entry("rep-015-oil-gas-linkage-regimes", "GO", ["databento_henry_hub", "US-OIL EIA WTI spot/fixed-rank futures candidates"], "deep_public_market_route_ready_benchmark_match_pending", "Henry Hub has 2010-06-06 through 2026-08-12 canonical coverage; EIA WTI routes provide deeper history, so Henry Hub overlap is at least bounded by about 195 monthly observations once exact benchmark semantics are fixed", "Monthly oil/gas observations are serially dependent and structural-regime comparisons reduce independent regime information.", "195 months is an upper-bound overlap screen for the current canonical Henry Hub era; final N_eff requires the exact benchmark, monthly construction and regime specification.", "Literature anchors regime weakening qualitatively; numeric coefficient-change MEPI remains to be recovered or decision-anchored.", "Raw monthly standardized screen is about 0.201 SD at N=195 before serial dependence and regime split; final detectable regime difference will be larger.", "No access blocker is evident. Exact benchmark/frequency/regime semantics must be fixed before market outcomes are read.", ["pin exact paper-compatible WTI benchmark and monthly timing", "fix literature-derived regime/break rule", "derive numeric MEPI and block/break-test power"]),
entry("rep-016-europe-us-transmission-limited", "GO", ["LIT-RS-EUUS author-linked RepOD replication package"], "exact_replication_route_identified", "Exact source-study sample is available through the author-linked replication package; usable structural-system N awaits package import/integrity verification", "Monthly structural-VAR observations and impulse responses are serially dependent; identification and bootstrap uncertainty determine effective information.", "No defensible N_eff until the exact package sample and VAR lag/identification structure are loaded.", "Use the source-study economic-smallness result to derive a predeclared transmission MEPI after the exact reported scale is recovered.", "Not computable before exact package/sample/VAR recovery.", "Exact replication data/code availability makes the reproduction route feasible; independent ICE/ENTSOG/GIE reconstruction remains a later separate fidelity route.", ["import/hash RepOD package", "verify runnable environment and exact structural estimand", "recover numeric economic-smallness anchor", "bootstrap identification/power sensitivity"]),
]
rows += [
entry("ctx-017-connectedness-congestion", "HOLD", ["Farag-Ruhnau 2026 contextual European evidence"], "contextual_only_not_henry_hub_reproduction", "No Henry Hub reproduction sample is defined because this source is explicitly contextual European evidence", "Not applicable until a distinct Henry Hub-specific cross-market design is justified by direct evidence.", "Not applicable for this contextual-only record.", "No Henry Hub scientific MEPI is derivable from this contextual source alone.", "Not applicable.", "Hold empirical execution. Retain only as a design constraint: separate contemporaneous from lagged transmission and represent congestion/capacity in any later direct Henry Hub design.", ["direct Henry Hub literature or separately justified target design required before empirical execution"]),
entry("rep-018-announcement-day-return-puzzle", "HOLD", ["databento_henry_hub", "eia_storage PIT release calendar", "historically fixed storage consensus pending"], "announcement_calendar_ready_full_near_replication_controls_not_ready", "106 verified release events join canonical market dates; surprise-controlled eligible N is unknown until a fixed pre-release consensus history is proven", "Release-event samples are sparse and calendar dependent; source-period and extended-period effects must be separated rather than pooled to rescue a result.", "106 events is only the unadjusted announcement-count screen. Full-design N_eff is undefined until consensus-qualified events and source-period coverage are known.", "The published anomaly supplies qualitative and magnitude context, but the design's required surprise-controlled MEPI must be fixed from source-period evidence before execution.", "Not computable for the declared full near replication until consensus-qualified N is established.", "The basic announcement-day contrast is technically constructible, but it cannot satisfy the declared full near-replication design without PIT surprise controls.", ["prove historically fixed pre-release consensus history", "count consensus-qualified source-period and extended-period events", "derive MEPI and calendar-preserving power"]),
entry("rep-019-friday-attention-effect", "HOLD", ["LIT-GKS-ATTENTION-DATA Genesis Financial Technologies plus Bloomberg", "databento_henry_hub near-replication candidate", "historically fixed storage consensus pending"], "exact_subscription_route_identified_near_replication_underpowered_on_retained_pit_window", "Current retained EIA release window has 97 Thursday and only 3 Friday releases; exact source-study sample requires subscription data and has not been imported", "Friday events are extremely sparse and event responses require surprise controls; holiday/event composition creates additional clustering/heterogeneity.", "Current retained PIT window has only 3 Friday events, so its effective information is bounded by that tiny cell even before dependence adjustment.", "External magnitude anchor is approximately 74% weaker Friday response; exact effect-scale translation requires the source-study response normalization and surprise series.", "Rough standardized two-group screen with 3 Friday versus 97 Thursday events is about 1.64 SD before covariates/dependence, far too coarse for a serious near replication.", "Do not execute on the retained PIT window as though it could resolve the published effect. Exact data entitlement or materially deeper near-replication history is required.", ["verify/import Genesis plus Bloomberg source-study data or prove an adequate near-replication history", "obtain PIT storage consensus", "recount Friday/Thursday qualified events", "run event-composition and power simulation"]),
]
rows += [
entry("rep-020-positioning-incremental-information", "REDESIGN", ["cftc_cot", "physical-control sources require frequency/semantic alignment"], "pit_positioning_ready_primary_measure_selection_needs_redesign", "136 release-correct weekly CFTC observations from 2024-01-02 through 2026-08-04; 135 weekly changes", "Managed Money net levels are highly persistent (AR1 about 0.907), whereas first differences are much less persistent (AR1 about 0.166). Physical controls add further mixed-frequency dependence.", "AR1 screen: levels N_eff about 6.63; weekly changes N_eff about 96.47. Treating levels and changes as interchangeable primary candidates would materially misstate power and create selection risk.", "The incremental-information MEPI must be defined on a fixed primary positioning representation after physical-control semantics are fixed.", "Rough standardized screen is about 1.09 SD for persistent levels versus 0.285 SD for weekly changes before control/multiple-testing inflation.", "Redesign the primary around a predeclared change-based positioning measure; retain persistent levels as secondary/contextual unless a specific literature estimand requires them.", ["fix weekly-change positioning representation as primary or justify another single primary", "fix physical-control frequency and publication semantics", "derive incremental-block MEPI and HAC/block power", "retain level/change multiplicity explicitly"]),
entry("exp-021-issued-weather-revisions", "GO", ["open_meteo_v1 immutable issued forecast runs"], "exploratory_issued_vintage_route_ready_not_a_literature_reproduction", "723 immutable issued snapshots from 2024-08-13 through 2026-08-12; at most 722 ordered prior/current run pairs before same-valid-time completeness, cutoff and gap filters", "Forecast revisions overlap heavily across valid times and the retained archive spans only about two annual cycles; raw run-pair count strongly overstates independent seasonal/regime information.", "No single N_eff is assigned before the same-valid-time revision vector, lead aggregation and market cutoff are fixed. Annual-cycle information remains intrinsically limited.", "No literature-reproduction MEPI exists. Any exploratory MEPI must be programme-decision-anchored and cannot be retroactively promoted as confirmation evidence.", "Not yet computable; raw 722-pair upper bound is not a valid power N.", "The raw issued-vintage corpus can support faithful revision construction, so exploratory implementation is feasible. GO is explicitly exploratory-only and confers no reproduction, confirmation or freeze authority.", ["fix same-valid-time revision construction and completeness rule", "fix lead/geographic aggregation without outcome tuning", "prove market-cutoff availability for each run", "derive exploratory decision MEPI and dependence-aware sensitivity"]),
]

decision_order = ("GO", "HOLD", "REDESIGN")
counts = {decision: sum(row["decision"] == decision for row in rows) for decision in decision_order}
payload = {
    "schema_version": 1,
    "programme_id": "002-henry-hub-fresh",
    "status": "non_outcome_feasibility_complete_unfrozen",
    "role": "supporting_design_level_feasibility_detail",
    "canonical_feasibility_owner": "research/programmes/002-henry-hub-fresh/evidence-map.json",
    "source_scan_ref": ".work/changes/289-l0-l3-henry-hub-research/feasibility-scan.json",
    "outcome_effect_testing_performed": False,
    "protected_evidence_opened": False,
    "empirical_execution_authority": False,
    "preregistration_freeze_authority": False,
    "decision_counts": counts,
    "entries": rows,
}
assert len(rows) == 21
assert sum(counts.values()) == 21
assert all(not row["freeze_ready"] and not row["empirical_execution_authority"] for row in rows)
OUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(json.dumps({"output": str(OUT), "entries": len(rows), "decision_counts": counts}, indent=2))
